version: '2'
services:
  todo1-app:
    image: todo1
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://todo1-mysql:3306/todo1?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://todo1-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://todo1-elasticsearch:9200
    ports:
      - 8080:8080
  todo1-mysql:
    extends:
      file: mysql.yml
      service: todo1-mysql
  todo1-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: todo1-elasticsearch
